[project]
name = "drydock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.17.0",
    "pyyaml>=6.0.3",
    "rich>=14.2.0",
    "docker>=7.0.0",
]
